config/routes.rb
Rails.application.routes.draw do
  get 'schedules_admin/index',to: 'schedules_admin#index'

  devise_for :admins, controllers: {
    sessions:  'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  
   devise_for :users, controllers: {
     sessions: 'users/sessions',
     passwords: 'users/passwords',
     registrations: 'users/registrations'
   }
  get '/schedules/start_time' , to: 'schedules#start_time'
  get '/schedules/end_time', to: 'schedules#end_time'
  get '/schedules/my_index', to: 'schedules#my_index'


 
  root 'pages#home'
  get 'pages/user_page'
  get 'pages/kanri'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="top-wrapper text-center">
  <div class="container">
    <!--今日の日付が出るようにする-->
    <div class="row">
      <div class="col-md-auto">
          <h1 class="date">2021年x月x日</h1>
          <div class="col-md-auto">
            <h1 class="date-time">只今の時刻</h1>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/kanri.html.erb
<div class="top-wrapper text-center">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="row">
          <div class="col-md-6">
            <%= link_to 'シフト作成', '#', class: 'btn btn-block btn-blue' %>
          </div>
          <div class="col-md-6">
            <%= link_to '従業員管理', '#',class: 'btn btn-block btn-blue' %>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="row">
          <div class="col-md-6">
            <%= link_to '出勤', start_time_path,class: 'btn btn-block btn-blue' %>
          </div>
          <div class="col-md-6">
            <%= link_to '退勤', end_time_path,class: 'btn btn-block btn-blue' %>
          </div>
        </div>
      </div>
    </div>
    
    <!--店長のみ勤怠を修正-->
    <% if current_user.task == "1" %>
    <div class="row">
      <div class= "col-md-6 mx-auto">
        <%= link_to '勤怠修正','#', class: 'btn btn-block btn-blue'%>  
      </div>
    </div>
    <% end %>
    
  </div>  
</div>

app/views/pages/user_page.html.erb
<div class="top-wrapper text-center">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="row">
          <div class="col-md-6">
            <%= link_to '出勤', '/schedules/start_time',class: 'btn btn-block btn-blue' %>
          </div>
          <div class="col-md-6">
            <%= link_to '退勤', '/schedules/end_time',class: 'btn btn-block btn-blue' %>
          </div>
        </div>
      </div>
    </div>
    
    
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="row">
          <div class="col-md-6">
            <%= link_to '勤怠一覧', schedules_my_index_path , class: 'btn btn-block btn-blue' %>
          </div>
          <div class="col-md-6">
            <%= link_to '給与明細発行', '#',class: 'btn btn-block btn-blue' %>
          </div>
        </div>
      </div>
    </div>
  </div>  
</div>