config/routes.rb
Rails.application.routes.draw do
  get 'schedules_admin/index',to: 'schedules_admin#index'

  devise_for :admins, controllers: {
    sessions:  'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  
   devise_for :users, controllers: {
     sessions: 'users/sessions',
     passwords: 'users/passwords',
     registrations: 'users/registrations'
   }
  get '/schedules/start_time' , to: 'schedules#start_time'
  get '/schedules/end_time', to: 'schedules#end_time'
  get '/schedules/my_index', to: 'schedules#my_index'


 
  root 'pages#home'
  get 'pages/user_page'
  get 'pages/kanri'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>DeviseRails5</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
         <% flash.each do |key, value|%>
          <div class="alert alert-<%= key%>" role="alert">
            <%= value %>
          </div>
        <% end %>
        <header>
            <nav>
                <% if user_signed_in? %>
                <%= link_to current_user.name, pages_user_page_path %>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
                <% else %>
                <%= link_to 'ログイン', new_user_session_path %>
                <%= link_to 'サインアップ', new_user_registration_path %>
                <% end %>
            </nav>
            <nav>
                <% if admin_signed_in? %>
                <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
                <% elsif user_signed_in? == false %>
                <%= link_to '管理者ログイン', new_admin_session_path %>
                <% end %>
            </nav>
        </header>

        <%= yield %>
    </body>
</html>